In [122]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

In [124]:
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [126]:
print(df.shape)
print("\n\n")
print(df.columns)
print("\n\n")
print(df.isna())

(51, 6)



Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')



    Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
0                 False                   False                     False
1                 False                   False                     False
2                 False                   False                     False
3                 False                   False                     False
4                 False                   False                     False
5                 False                   False                     False
6                 False                   False                     False
7                 False                   False                     False
8                 False                   False                     False
9                 False                   False                     False
10                False                   False                     False
11                False                   False                     False
12                False                   False                     False
13                False                   False                     False
14                False                   False                     False
15                False                   False                     False
16                False                   False                     False
17                False                   False                     False
18                False                   False                     False
19                False                   False                     False
20                False                   False                     False
21                False                   False                     False
22                False                   False                     False
23                False                   False                     False
24                False                   False                     False
25                False                   False                     False
26                False                   False                     False
27                False                   False                     False
28                False                   False                     False
29                False                   False                     False
30                False                   False                     False
31                False                   False                     False
32                False                   False                     False
33                False                   False                     False
34                False                   False                     False
35                False                   False                     False
36                False                   False                     False
37                False                   False                     False
38                False                   False                     False
39                False                   False                     False
40                False                   False                     False
41                False                   False                     False
42                False                   False                     False
43                False                   False                     False
44                False                   False                     False
45                False                   False                     False
46                False                   False                     False
47                False                   False                     False
48                False                   False                     False
49                False                   False                     False
50                False                    True                      True

    Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary  \
0                               False                              False
1                               False                              False
2                               False                              False
3                               False                              False
4                               False                              False
5                               False                              False
6                               False                              False
7                               False                              False
8                               False                              False
9                               False                              False
10                              False                              False
11                              False                              False
12                              False                              False
13                              False                              False
14                              False                              False
15                              False                              False
16                              False                              False
17                              False                              False
18                              False                              False
19                              False                              False
20                              False                              False
21                              False                              False
22                              False                              False
23                              False                              False
24                              False                              False
25                              False                              False
26                              False                              False
27                              False                              False
28                              False                              False
29                              False                              False
30                              False                              False
31                              False                              False
32                              False                              False
33                              False                              False
34                              False                              False
35                              False                              False
36                              False                              False
37                              False                              False
38                              False                              False
39                              False                              False
40                              False                              False
41                              False                              False
42                              False                              False
43                              False                              False
44                              False                              False
45                              False                              False
46                              False                              False
47                              False                              False
48                              False                              False
49                              False                              False
50                               True                               True

    Group
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10  False
11  False
12  False
13  False
14  False
15  False
16  False
17  False
18  False
19  False
20  False
21  False
22  False
23  False
24  False
25  False
26  False
27  False
28  False
29  False
30  False
31  False
32  False
33  False
34  False
35  False
36  False
37  False
38  False
39  False
40  False
41  False
42  False
43  False
44  False
45  False
46  False
47  False
48  False
49  False
50   True

In [128]:
clean_df = df.dropna()
clean_df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business
5,Art History,"35,800.00","64,900.00","28,800.00","125,000.00",HASS
6,Biology,"38,800.00","64,800.00","36,900.00","135,000.00",STEM
7,Business Management,"43,000.00","72,100.00","38,800.00","147,000.00",Business
8,Chemical Engineering,"63,200.00","107,000.00","71,900.00","194,000.00",STEM
9,Chemistry,"42,600.00","79,900.00","45,300.00","148,000.00",STEM
10,Civil Engineering,"53,900.00","90,500.00","63,400.00","148,000.00",STEM
11,Communications,"38,100.00","70,000.00","37,500.00","143,000.00",HASS
12,Computer Engineering,"61,400.00","105,000.00","66,100.00","162,000.00",STEM
13,Computer Science,"55,900.00","95,500.00","56,000.00","154,000.00",STEM
14,Construction,"53,700.00","88,900.00","56,300.00","171,000.00",Business
15,Criminal Justice,"35,000.00","56,300.00","32,200.00","107,000.00",HASS
16,Drama,"35,900.00","56,900.00","36,700.00","153,000.00",HASS
17,Economics,"50,100.00","98,600.00","50,600.00","210,000.00",Business
18,Education,"34,900.00","52,000.00","29,300.00","102,000.00",HASS
19,Electrical Engineering,"60,900.00","103,000.00","69,300.00","168,000.00",STEM
20,English,"38,000.00","64,700.00","33,400.00","133,000.00",HASS
21,Film,"37,900.00","68,500.00","33,900.00","136,000.00",HASS
22,Finance,"47,900.00","88,300.00","47,200.00","195,000.00",Business
23,Forestry,"39,100.00","62,600.00","41,000.00","111,000.00",Business
24,Geography,"41,200.00","65,500.00","40,000.00","132,000.00",HASS
25,Geology,"43,500.00","79,500.00","45,000.00","156,000.00",STEM
26,Graphic Design,"35,700.00","59,800.00","36,000.00","112,000.00",HASS
27,Health Care Administration,"38,800.00","60,600.00","34,600.00","101,000.00",Business
28,History,"39,200.00","71,000.00","37,000.00","149,000.00",HASS
29,Hospitality & Tourism,"37,800.00","57,500.00","35,500.00","124,000.00",Business
30,Industrial Engineering,"57,700.00","94,700.00","57,100.00","173,000.00",STEM
31,Information Technology (IT),"49,100.00","74,800.00","44,500.00","129,000.00",STEM
32,Interior Design,"36,100.00","53,200.00","35,700.00","107,000.00",HASS
33,International Relations,"40,900.00","80,900.00","38,200.00","157,000.00",HASS
34,Journalism,"35,600.00","66,700.00","38,400.00","145,000.00",HASS
35,Management Information Systems (MIS),"49,200.00","82,300.00","45,300.00","146,000.00",STEM
36,Marketing,"40,800.00","79,600.00","42,100.00","175,000.00",Business
37,Math,"45,400.00","92,400.00","45,200.00","183,000.00",STEM
38,Mechanical Engineering,"57,900.00","93,600.00","63,700.00","163,000.00",STEM
39,Music,"35,900.00","55,000.00","26,700.00","134,000.00",HASS
40,Nursing,"54,200.00","67,000.00","47,600.00","98,300.00",Business
41,Nutrition,"39,900.00","55,300.00","33,900.00","99,200.00",HASS
42,Philosophy,"39,900.00","81,200.00","35,500.00","168,000.00",HASS
43,Physician Assistant,"74,300.00","91,700.00","66,400.00","124,000.00",STEM
44,Physics,"50,300.00","97,300.00","56,000.00","178,000.00",STEM
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [130]:
print(clean_df['Starting Median Salary'])
print("\n\n")
print(clean_df['Starting Median Salary'].max())
print("\n\n")
print(clean_df['Starting Median Salary'].idxmax())
print("\n\n")
print(clean_df['Undergraduate Major'].loc[43])
print("\n\n")
print(clean_df['Undergraduate Major'][43])
print("\n\n")
print(clean_df.loc[43])

0    46,000.00
1    57,700.00
2    42,600.00
3    36,800.00
4    41,600.00
5    35,800.00
6    38,800.00
7    43,000.00
8    63,200.00
9    42,600.00
10   53,900.00
11   38,100.00
12   61,400.00
13   55,900.00
14   53,700.00
15   35,000.00
16   35,900.00
17   50,100.00
18   34,900.00
19   60,900.00
20   38,000.00
21   37,900.00
22   47,900.00
23   39,100.00
24   41,200.00
25   43,500.00
26   35,700.00
27   38,800.00
28   39,200.00
29   37,800.00
30   57,700.00
31   49,100.00
32   36,100.00
33   40,900.00
34   35,600.00
35   49,200.00
36   40,800.00
37   45,400.00
38   57,900.00
39   35,900.00
40   54,200.00
41   39,900.00
42   39,900.00
43   74,300.00
44   50,300.00
45   40,800.00
46   35,900.00
47   34,100.00
48   36,500.00
49   34,000.00
Name: Starting Median Salary, dtype: float64



74300.0



43



Physician Assistant



Physician Assistant



Undergraduate Major                  Physician Assistant
Starting Median Salary                         74,300.00
Mid-Career Median Salary                       91,700.00
Mid-Career 10th Percentile Salary              66,400.00
Mid-Career 90th Percentile Salary             124,000.00
Group                                               STEM
Name: 43, dtype: object

In [132]:
highest_mid_career_salary = clean_df['Mid-Career Median Salary'].max()
highest_mid_career_salary_idx = clean_df['Mid-Career Median Salary'].idxmax()
print(f"Highest Mid-Career Salary is ${highest_mid_career_salary} for {clean_df['Undergraduate Major'][highest_mid_career_salary_idx]} majors")

Highest Mid-Career Salary is $107000.0 for Chemical Engineering majors

In [134]:
lowest_start_career_salary = clean_df['Starting Median Salary'].min()
lowest_start_career_salary_idx = clean_df['Starting Median Salary'].idxmin()
print(f"Lowest Starting Salary is ${lowest_start_career_salary} for {clean_df['Undergraduate Major'][lowest_mid_career_salary_idx]} majors")

Lowest Starting Salary is $34000.0 for Education majors

In [136]:
lowest_mid_career_salary = clean_df['Mid-Career Median Salary'].min()
lowest_mid_career_salary_idx = clean_df['Mid-Career Median Salary'].idxmin()
print(f"Lowest Mid-Career Salary is ${lowest_mid_career_salary} for {clean_df['Undergraduate Major'][lowest_mid_career_salary_idx]} majors")

Lowest Mid-Career Salary is $52000.0 for Education majors

In [138]:
# clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
# clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"109,800.00","46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"113,700.00","42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"104,200.00","36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"85,400.00","41,600.00","76,800.00","50,600.00","136,000.00",Business

In [140]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major    Spread
40                     Nursing 50,700.00
43         Physician Assistant 57,600.00
41                   Nutrition 65,300.00
49                     Spanish 65,400.00
27  Health Care Administration 66,400.00

In [142]:
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                         210,000.00
22               Finance                         195,000.00
8   Chemical Engineering                         194,000.00
37                  Math                         183,000.00
44               Physics                         178,000.00

In [144]:
greatest_spread = clean_df.sort_values('Spread', ascending=False)
greatest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major     Spread
17           Economics 159,400.00
22             Finance 147,800.00
37                Math 137,800.00
36           Marketing 132,900.00
42          Philosophy 132,500.00

In [146]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16